# Generated by Django 4.0.4 on 2023-02-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
