# Generated by Django 4.0.4 on 2022-09-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='/sample.jpg', null=True, upload_to='', verbose_name='category image'),
        ),
    ]
